
name: Docker Build and Push
on:
  workflow_call:
    secrets:
      ROBOT_REGISTRY_USERNAME:
        required: true
      ROBOT_REGISTRY_PASSWORD:
        required: true
    inputs:
      harbor_project:
        required: true
        type: string
      service_name:
        required: true
        type: string
      git_branch:
        required: true
        type: string
      git_sha_short:
        required: true
        type: string
      git_tag:
        required: true
        type: string
      docker-extra-args:  ## TODO validation
        required: false
        type: string
    outputs:
      image_tag:
        value: ${{ jobs.docker_build_push.outputs.image_tag }}
jobs:
  docker_build_push:
    env:
      REGISTRY_URL: registry-emea.app.corpintra.net
    runs-on: [road-runner, small]
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }} 
    steps:
      - name: Docker Build and Push
        uses: action/docker-build-and-push@v3
        with:
          registry_url: $REGISTRY_URL
          username: ${{ secrets.ROBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.ROBOT_REGISTRY_PASSWORD }}
          push: true
          context: ${{ github.workspace }}
          dockerfile_name: Dockerfile
          build_args: |
            ${{ inputs.docker-extra-args }}
          tags: |
            ${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_sha_short }}
            ${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_tag }}

      - name: Output image tag
        id: image_tag
        run: |
          IMAGE_TAG=$REGISTRY_URL/${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_tag }}
          echo "image_tag=$(echo $IMAGE_TAG)" >> $GITHUB_OUTPUT
          