
name: Docker Build and Push
on:
  workflow_call:
    secrets:
      ROBOT_REGISTRY_USERNAME:
        required: true
      ROBOT_REGISTRY_PASSWORD:
        required: true
    inputs:
      harbor_project:
        required: true
        type: string
      service_name:
        required: true
        type: string
      git_branch:
        required: true
        type: string
      git_sha_short:
        required: true
        type: string
      git_tag:
        required: true
        type: string
      docker-extra-args:
        required: false
        type: string
    outputs:
      image_tag:
        value: ${{ jobs.docker_build_push.outputs.image_tag }}
jobs:
  docker_build_push:
    env:
      REGISTRY_URL: registry-emea.app.corpintra.net
    runs-on: [road-runner, small]
    outputs:
      image_tag: ${{ steps.docker_build_push.outputs.image_tag }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0
        
      - name: Git Pull
        run: git pull origin ${{ inputs.git_branch }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: target

      - name: Docker Login
        env:
          ROBOT_REGISTRY_USERNAME: ${{ secrets.ROBOT_REGISTRY_USERNAME }}
          ROBOT_REGISTRY_PASSWORD: ${{ secrets.ROBOT_REGISTRY_PASSWORD }}
        run: |
          docker login -u="$ROBOT_REGISTRY_USERNAME" -p="$ROBOT_REGISTRY_PASSWORD" $REGISTRY_URL
        
      - name: Docker Build and Push
        id: docker_build_push
        run: |
          IMAGE_SHA=$REGISTRY_URL/${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_sha_short }}
          IMAGE_TAG=$REGISTRY_URL/${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_tag }}

          docker build -t --no-cache $IMAGE_SHA ${{ inputs.docker-extra-args }} .  
          docker tag $IMAGE_SHA $IMAGE_TAG

          docker push $IMAGE_SHA
          docker push $IMAGE_TAG

          echo "image_tag=$(echo $IMAGE_TAG)" >> $GITHUB_OUTPUT
          