
name: Docker Build and Push
on:
  workflow_call:
    secret:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
    inputs:
      harbor_project:
        required: true
        type: string
      service_name:
        required: true
        type: string
      git_tag:
        required: true
        type: string
      git_sha_short:
        required: true
        type: string
      docker-extra-args:
        required: false
        type: string

  jobs:
    docker_build_push:
      env:
        REGISTRY_URL: registry-emea.app.corpintra.net
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            ref: ${{ inputs.git_tag }}
            fetch-depth: 0
        
        - name: Git Pull
          run: git pull origin ${{ inputs.git_tag }}

        - name: Docker Login
          env:
            REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
            REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          run: |
            docker login -u="$REGISTRY_USERNAME" -p="$REGISTRY_PASSWORD" $REGISTRY_URL
        
        - name: Docker Build and Push
          run: |
            IMAGE_SHA=$REGISTRY_URL/${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_sha_short }}
            IMAGE_TAG=$REGISTRY_URL/${{ inputs.harbor_project }}/${{ inputs.service_name }}:${{ inputs.git_tag }}

            docker build -t --no-cache $IMAGE_SHA ${{ input.docker-extra-args }} .
            docker tag $IMAGE_SHA $IMAGE_BRANCH
            docker push $IMAGE_SHA
            docker push $IMAGE_BRANCH

      