
name: Initialization
on:
  workflow_call:
    outputs:
      git_branch:
        value: ${{ jobs.initialize.outputs.git_branch }}
      git_sha_short:
        value: ${{ jobs.initialize.outputs.git_sha_short }}

jobs:
  initialize:
    runs-on: [road-runner, small]
    outputs:
      git_branch: ${{ steps.set_git_branch.outputs.git_branch }}
      git_sha_short: ${{ steps.set_git_branch.outputs.git_sha_short }}
    steps:
      - name: Set git branch
        id: set_git_branch
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ $TAG == "refs/heads/"* ]]; then
            echo "git_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
            echo "git_sha_short=$(echo ${GITHUB_SHA::6})" >> $GITHUB_OUTPUT
          else
            echo "git_branch=$(echo $TAG)" >> $GITHUB_OUTPUT
            echo "git_sha_short=$(echo $TAG)" >> $GITHUB_OUTPUT
          fi
      