
name: Sonarqube and BlackDuck Scan
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      BLACKDUCK_TOKEN:
        required: true
      ARTIFACTORY_USERNAME: ## NEED PREPARE
        required: true
      ARTIFACTORY_ACCESSTOKEN: ## NEED PREPARE
        required: true
    inputs:
      git_branch:
        required: true
        type: string
      service_name:
        required: true
        type: string
      sonar_branch:
        required: true
        type: string
      blackduck_project_name:
        required: true
        type: string
      blackduck_rapid_scan:
        required: false
        type: string
        default: 'false'
      blackduck_phase:
        required: true
        type: string
      blackduck_project_version:
        required: true
        type: string
      setup_local_database:
        required: false
        type: string
        default: 'false'
jobs:
  security-scanning:
    env: 
      SONAR_HOST: https://go40-sonar.dot.i.mercedes-benz.com
      SONAR_PROJECT_KEY: ${{ inputs.service_name }}
      SONAR_BRANCH: ${{ inputs.sonar_branch }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_SCANNER_IMAGE: registry-emea.app.corpintra.net/dockerhub/sonarsource/sonar-scanner-cli:latest
      BLACKDUCK_SERVER: bdscan.i.mercedes-benz.com
      BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
      BLACKDUCK_PROJECT_NAME: ${{ inputs.blackduck_project_name }}
      BLACKDUCK_SOURCE_CODE: ${{ inputs.service_name }}
      BLACKDUCK_TIMEOUT: 300
      BLACKDUCK_PHASE: ${{ inputs.blackduck_phase }}
      BLACKDUCK_PROJECT_VERSION: ${{ inputs.blackduck_project_version }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_ACCESSTOKEN: ${{ secrets.ARTIFACTORY_ACCESSTOKEN }}
    runs-on: [road-runner, small]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0
        
      - name: Git Pull
        run: git pull origin ${{ inputs.git_branch }}

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # cache: 'maven'
    
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      ## Setup Local database
      - name: Setup Postgres for Unit Test
        run: |
          if [[ '${{ inputs.setup_local_database }}' == 'true' ]]; then
            echo "Setup Postgres for Unit Test"

            docker rm -f test-postgres || true
            docker run --name test-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d registry-emea.app.corpintra.net/dmo/postgresql@sha256:e1e915f72f648f55356b53cc5a4bc2f0af34b27bb202cd61eb94801c20eaf883
            until nc -z localhost 5432
            do 
              echo "waiting for postgres container..."
              sleep 1.0
            done

            echo "Postgres is up and running"
          else
            echo "Skip Setup Postgres for Unit Test"
          fi

      - name: Artifactory Settings.xml
        run : |
          sed -i "s#REPO_USERNAME#$ARTIFACTORY_USERNAME#" settings.xml
          sed -i "s#REPO_TOKEN#$ARTIFACTORY_ACCESSTOKEN#" settings.xml     
          cat settings.xml

      - name: Maven Package
        continue-on-error: true
        run: mvn clean package -s settings.xml

      ## Remove Local database
      - name: Remove Postgres for Unit Test
        run: |
          if [[ '${{ inputs.setup_local_database }}' == 'true' ]]; then
            echo "Remove Postgres for Unit Test"
            docker rm -f test-postgres || true
          else
            echo "Skip Remove Postgres for Unit Test"
          fi

      - name: Update sonarqube properties and settings.xml
        run: |
          sed -i "s#SONAR_HOST_URL#$SONAR_HOST#" sonar-project.properties
          sed -i "s#SONAR_LOGIN#$SONAR_TOKEN#" sonar-project.properties
          sed -i "s#SONAR_PROJECT_KEY#$SONAR_PROJECT_KEY#" sonar-project.properties
          sed -i "s#SONAR_BRANCH#$SONAR_BRANCH#" sonar-project.properties
          sed -i "s#REPO_USERNAME#$ARTIFACTORY_USERNAME#" settings.xml
          sed -i "s#REPO_TOKEN#$ARTIFACTORY_ACCESSTOKEN#" settings.xml

          cat sonar-project.properties
          cat settings.xml

      - name: Sonarqube Scan
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL="http://${SONAR_HOST}"  \
            -v "${{ github.workspace }}:/usr/src" \
            ${SONAR_SCANNER_IMAGE}

      - name: Sonarqube Quality Gate
        continue-on-error: true
        run: |
          curl --insecure -u${SONAR_TOKEN}: ${SONAR_HOST}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}'&'branch=${SONAR_BRANCH}  --noproxy '*' | jq .projectStatus.status | grep OK

      - name: BlackDuck Scan
        continue-on-error: true
        run: |
          if [[ '${{ inputs.blackduck_rapid_scan }}' == 'false' ]]; then
            echo "Running BlackDuck Scan"

            bash <(curl -s https://detect.synopsys.com/detect9.sh)\
              --blackduck.url="https://${BLACKDUCK_SERVER}"\
              --blackduck.api.token='$BLACKDUCK_TOKEN'\
              --detect.timeout="${BLACKDUCK_TIMEOUT}"\
              --detect.project.name="${BLACKDUCK_PROJECT_NAME}"\
              --detect.code.location.name="${BLACKDUCK_SOURCE_CODE}"\
              --detect.project.version.name="${BLACKDUCK_PROJECT_VERSION}"\
              --detect.project.version.phase="${BLACKDUCK_PHASE}"\
              --detect.maven.build.command="--settings settings.xml" \
              --logging.level.com.synopsys.integration="INFO" \
              --detect.cleanup=true \
              --detect.scan.output.path=. \
              --detect.swift.path=. \
              --detect.bdio.output.path=. \
              --detect.risk.report.pdf=true \
              --detect.maven.excluded.scopes='test' \
              --detect.policy.check.fail.on.severities=BLOCKER,CRITICAL,MAJOR
          else
            echo "Running BlackDuck Rapid Scan"

            bash <(curl -s https://detect.synopsys.com/detect9.sh)\
              --blackduck.url="https://${BLACKDUCK_SERVER}"\
              --blackduck.api.token='$BLACKDUCK_TOKEN'\
              --detect.timeout="${BLACKDUCK_TIMEOUT}"\
              --detect.project.name="${BLACKDUCK_PROJECT_NAME}"\
              --detect.code.location.name="${BLACKDUCK_SOURCE_CODE}"\
              --detect.project.version.name="${BLACKDUCK_PROJECT_VERSION}"\
              --detect.project.version.phase="${BLACKDUCK_PHASE}"\
              --detect.maven.build.command="--settings settings.xml" \
              --logging.level.com.synopsys.integration="INFO" \
              --detect.cleanup=true \
              --detect.scan.output.path=. \
              --detect.swift.path=. \
              --detect.bdio.output.path=. \
              --detect.risk.report.pdf=true \
              --detect.maven.excluded.scopes='test' \
              --detect.blackduck.scan.mode=RAPID \
              --detect.blackduck.rapid.compare.mode=BOM_COMPARE_STRICT
          fi