
name: Sonarqube, BlackDuck, Sechub Scan
on:
  workflow_call:
    inputs:
      git_branch:
        required: true
        type: string
      service_name:
        required: true
        type: string
      sonar_branch:
        required: true
        type: string
      blackduck_project_name:
        required: true
        type: string
      blackduck_rapid_scan:
        required: false
        type: string
        default: 'false'
      blackduck_phase:
        required: true
        type: string
      blackduck_project_version:
        required: true
        type: string
      setup_local_database:
        required: false
        type: string
        default: 'false'
      security_check_bypass:
        required: false
        type: boolean
        default: true
      sechub_branch:
        required: false
        type: string
        default: 'develop'
jobs:
  security-scanning:
    env: 
      SONAR_HOST: https://go40-sonar.dot.i.mercedes-benz.com
      SONAR_PROJECT_KEY: ${{ inputs.service_name }}
      SONAR_BRANCH: ${{ inputs.sonar_branch }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_SCANNER_IMAGE: registry-emea.app.corpintra.net/dockerhub/sonarsource/sonar-scanner-cli:latest
      BLACKDUCK_SERVER: bdscan.i.mercedes-benz.com
      BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
      BLACKDUCK_PROJECT_NAME: ${{ inputs.blackduck_project_name }}
      BLACKDUCK_SOURCE_CODE: ${{ inputs.service_name }}
      BLACKDUCK_TIMEOUT: 300
      BLACKDUCK_PHASE: ${{ inputs.blackduck_phase }}
      BLACKDUCK_PROJECT_VERSION: ${{ inputs.blackduck_project_version }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_ACCESSTOKEN: ${{ secrets.ARTIFACTORY_ACCESSTOKEN }}
      SECHUB_APITOKEN: ${{ secrets.SECHUB_APITOKEN }}
      SECHUB_USERID: ${{ secrets.SECHUB_USERID }}
      SECHUB_BRANCH: ${{ inputs.sechub_branch }}
      SECHUB_PROJECT_KEY: ${{ inputs.service_name }}
      
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0

      - name: Update sonarqube properties and settings.xml
        run: |
          sed -i "s|SONAR_HOST_URL|$SONAR_HOST|" sonar-project.properties
          sed -i "s|SONAR_LOGIN|$SONAR_TOKEN|" sonar-project.properties
          sed -i "s|SONAR_PROJECT_KEY|$SONAR_PROJECT_KEY|" sonar-project.properties
          sed -i "s|SONAR_BRANCH|$SONAR_BRANCH|" sonar-project.properties
          sed -i "s|REPO_USERNAME|$ARTIFACTORY_USERNAME|" settings.xml
          sed -i "s|REPO_TOKEN|$ARTIFACTORY_ACCESSTOKEN|" settings.xml
  
          cat sonar-project.properties
          cat settings.xml
        
      - name: Print blackduck_phase and sonar_branch
        run: |
          echo "BlackDuck Phase: ${{ inputs.blackduck_phase }}"
          echo "Sonar Branch: ${{ inputs.sonar_branch }}"
          echo "SONAR_PROJECT_KEYh: ${{ inputs.SONAR_PROJECT_KEY }}"
