
name: Maven Package
on:
  workflow_call:
    inputs:
      git_branch:
        required: true
        type: string
      maven_extra_args:
        required: false
        type: string

jobs:
  maven_package:
    runs-on: [road-runner, small]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_branch }}
          fetch-depth: 0
        
      - name: Git Pull
        run: git pull origin ${{ inputs.git_branch }}

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Package
        run: mvn clean package ${{ inputs.maven_extra_args }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target
