name: Terraform

on:
  workflow_call:
    secrets:
      ACCOUNT_ID_NONPROD:
        required: true
      AWS_ACCESS_KEY_ID_NONPROD:
        required: true
      AWS_SECRET_ACCESS_KEY_NONPROD:
        required: true
      ACCOUNT_ID_PROD:
        required: true
      AWS_ACCESS_KEY_ID_PROD:
        required: true
      AWS_SECRET_ACCESS_KEY_PROD:
        required: true
      AWS_REGION:
        required: true
    inputs:
      file_path: ## PROFILE
        required: true
        type: string
env:
  BACKEND_BUCKET_NONPROD: ce-state-849872024563-2010-r-2829-team
  BACKEND_BUCKET_PROD: ce-state-631567126211-2010-r1-1007-team

jobs:
  terraform: 
    runs-on: [os-small-amd64-linux]
    steps:
      - uses: actions/checkout@v3

      - name: Check env and module
        run: |
          filename=$(basename ${{ inputs.file_path }} | cut -d. -f1)
          if echo "$filename" | grep -iq "nonprod"; then
            echo "BACKEND_BUCKET=${{ env.BACKEND_BUCKET_NONPROD }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}" >> $GITHUB_ENV
            echo "AWS_ACCOUNT_ID=${{ secrets.ACCOUNT_ID_NONPROD }}" >> $GITHUB_ENV
          else
            echo "BACKEND_BUCKET=${{ env.BACKEND_BUCKET_PROD }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "AWS_ACCOUNT_ID=${{ secrets.ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
          fi

          module=$(echo ${{ inputs.file_path }} | cut -d'/' -f2)
          echo "MODULE=$module" >> $GITHUB_ENV
          
          echo "Module is ${{ env.MODULE }}"
          echo "Access Key is ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "Secret Key is ${{ env.AWS_SECRET_ACCESS_KEY }}"

      - uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform init
        env:
          AWS_TERRAFORM_BACKEND_BUCKET: ${{ env.BACKEND_BUCKET }}
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
          AWS_TERRAFORM_MODULE: ${{ env.MODULE }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          make PROFILE=$(basename ${{ inputs.file_path }} | cut -d. -f1) terraform.init

      - name: Terraform plan
        run: |
          make PROFILE=$(basename ${{ inputs.file_path }} | cut -d. -f1) terraform.plan
      
      - name: Terraform apply
        if: github.event.pull_request.merged == true
        run: |
          make PROFILE=$(basename ${{ inputs.file_path }} | cut -d. -f1) terraform.apply 